name: pyface
channels:
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python==3.11
  - pillow==10.4.0
  - PyYAML==6.0.2
  - tqdm==4.66.5
  - pip==24.2
  - pip:
    - -r file:requirements.txt


