[tool.black]
line-length = 120

[tool.isort]
profile = "black"
include_trailing_comma = true
use_parentheses = true
line_length = 120
lines_between_types = 1
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]

[tool.mypy]
show_error_codes = true
ignore_missing_imports = true
follow_imports = "silent"
no_strict_optional = true
verbosity = 0

[tool.flake8]
max-line-length = 120
